[package]
name = "cymule"
description = "Rust authoring and engine client SDK for Cymule"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
publish.workspace = true

[dependencies]
cymule-core.workspace = true
cymule-durable.workspace = true
cymule-durable-protocol.workspace = true
cymule-evolution.workspace = true
cymule-resource.workspace = true
cymule-runtime.workspace = true
cymule-virtual.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
