[package]
name = "cymule-authenticated-collections"
description = "Provider-neutral authenticated persistent collections for Cymule"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
